/*
 * OPRoS Component Engine (OCE)
 * Copyright (c) 2008 ETRI. http://www.etri.re.kr.
 * Distributed under the OPRoS License, Version 2.0.
 *
 *  @Created : 2014. 6. 10
 *  @Author  : sby (sby@etri.re.kr)
 *
 *  @File    : opros_common_inc.inc
 *
 */

#ifndef _OPROS_COMMON_INC_INC_
#define _OPROS_COMMON_INC_INC_


#define opros_internal_COMPONENT_RESOURCE_PATH "_opros_xx_internal_xx_Component_Path"

#endif /* _OPROS_COMMON_INC_INC_ */
