#ifndef MODSERVICEMANAGERCONFIG_H
#define MODSERVICEMANAGERCONFIG_H

//#define MOD_OPROS_SERVICEMANAGER_USE_CONSOLE
//#define MOD_OPROS_SERVICEMANAGER_USE_TASK

#endif //MODSERVICEMANAGERCONFIG_H
